# Generated by Django 4.2.5 on 2023-09-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intelligence_needed_to_perform', models.IntegerField()),
                ('effect_on_health', models.IntegerField()),
                ('effect_on_mental', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labyrinth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('is_lab_entrance', models.BooleanField()),
                ('is_lab_exit', models.BooleanField()),
                ('available_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.room')),
                ('labyrinth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.labyrinth')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField()),
                ('effect_on_health', models.IntegerField()),
                ('effect_on_mental', models.IntegerField()),
                ('effect_on_intelligence', models.IntegerField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.room')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intelligence', models.IntegerField()),
                ('health', models.IntegerField()),
                ('mental', models.IntegerField()),
                ('current_room', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.room')),
            ],
        ),
    ]
