# Generated by Django 4.2.5 on 2023-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='effect_on_health',
        ),
        migrations.RemoveField(
            model_name='action',
            name='effect_on_mental',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='effect_on_health',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='effect_on_intelligence',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='effect_on_mental',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='room',
        ),
    ]
