# Generated by Django 4.2.5 on 2023-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_roomobjective_remove_action_effect_on_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_exit',
        ),
        migrations.AddField(
            model_name='room',
            name='available_exit',
            field=models.ManyToManyField(to='objects.room'),
        ),
    ]
