# Generated by Django 4.2.5 on 2023-10-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_remove_room_available_exit_room_available_exit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='available_exit',
            new_name='available_exits',
        ),
    ]
