# Generated by Django 4.2.5 on 2023-10-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_available_exit_room_available_exits'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labyrinth',
            table='objects_labyrinth',
        ),
        migrations.AlterModelTable(
            name='room',
            table='objects_room',
        ),
    ]
