# Generated by Django 4.2.5 on 2023-09-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleitem',
            name='effect_on_health',
        ),
        migrations.RemoveField(
            model_name='ruleitem',
            name='effect_on_intelligence',
        ),
        migrations.RemoveField(
            model_name='ruleitem',
            name='effect_on_mental',
        ),
        migrations.RemoveField(
            model_name='ruleitem',
            name='ruleSet',
        ),
        migrations.CreateModel(
            name='ObjectiveRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.IntegerField()),
                ('effect_on_health', models.IntegerField()),
                ('effect_on_mental', models.IntegerField()),
                ('effect_on_intelligence', models.IntegerField()),
                ('ruleItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.ruleitem')),
                ('ruleSet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='ActionRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('effect_on_health', models.IntegerField()),
                ('effect_on_mental', models.IntegerField()),
                ('effect_on_intelligence', models.IntegerField()),
                ('ruleItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.ruleitem')),
                ('ruleSet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.ruleset')),
            ],
        ),
    ]
