# Generated by Django 4.2.5 on 2023-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_remove_ruleitem_effect_on_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionruleitem',
            name='effect_on_health',
            field=models.FloatField(),
        ),
    ]
